import "./globals.css";
import { Lato } from 'next/font/google'

const lato = Lato({ subsets: ['latin'], weight: ['100', '300', '400', '700'] })

export const metadata = {
	title: "Spark Chat",
	description: "Generated by create next app",
	icons: {
		icon: "/icons/favicon.png",
		shortcut: "/icons/favicon.png",
		apple: "/icons/favicon.png",
		other: {
			safari: "/icons/favicon.png",
		},
	}
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${lato.className} antialiased`}>
				{children}
			</body>
		</html>
	);
}
